version: '3'
services:
  nodejs:
    build: 
      context: ./service
      dockerfile: Dockerfile
    image: pedrohsoaress/nodejs
    container_name: nodejs
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: nodedb
    volumes:
      - ./service:/usr/src/app
    networks:
      - node-network
      
  mysql:
    image: mysql:8.3
    container_name: mysql
    command: --authentication_policy=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 40s
      timeout: 180s
      retries: 5
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - node-network
  
  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    depends_on:
      - "nodejs"

networks:
  node-network:
    driver: bridge
    
